twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        RolesClass: 'App\BlogApp\Application\Config\Roles'
        PostStatusClass: 'App\BlogApp\Application\Config\PostStatus'

when@test:
    twig:
        strict_variables: true
