index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'app_posts'
        permanent: true

blogapp:
    resource: '../src/BlogApp/Infrastructure/Controller'
    prefix: /
    type: annotation
